# application.yml

spring:
  profiles:
    active: dev
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://sushehost:3307/staffjoy_account?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    jpa:
      show-sql: true

account:
  access-token: YOUR_ACCESS_TOKEN
  access-key: YOUR_ACCESS_KEY